runtime: python37

instance_class: F2

service: ml2lm

beta_settings:
  cloud_sql_instances: develop-187803:asia-northeast1:db000

entrypoint: bin/manage.py migrate && uwsgi --http :$PORT -y etc/uwsgi.yml

handlers:
  - url: /static
    static_dir: static/

includes:
  - secret.yaml
