runtime: python37

service: ml2lm

resources:
  cpu: 1
  memory_gb: 3
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: develop-187803:asia-northeast1:db000

entrypoint: bin/manage.py migrate && uwsgi --http :$PORT -y etc/uwsgi.yml

includes:
  - secret.yaml
