steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME/app:$COMMIT_SHA", "."]
    id: "django-build"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "run",
        "-e",
        "POSTGRES_USER=postgres",
        "-e",
        "POSTGRES_PASSWORD=password",
        "-e",
        "POSTGRES_DB=app",
        "--name",
        "postgres",
        "-itd",
        "postgres:9.6",
      ]
    id: "postgres-run"
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "run",
        "--rm",
        "-e",
        "DB_HOST=db",
        "-v",
        "/workspace:/var/www/app",
        "--link",
        "postgres:db",
        "gcr.io/$PROJECT_ID/$REPO_NAME/app:$COMMIT_SHA",
        "bin/manage.py",
        "test",
        "--",
        "-v",
      ]
    id: "django-test"
    waitFor: ["django-build", "postgres-run"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "kms",
        "decrypt",
        "--ciphertext-file=secret.yaml.enc",
        "--plaintext-file=secret.yaml",
        "--location=global",
        "--keyring=$REPO_NAME",
        "--key=secret",
      ]
    id: "decrypt-secret"
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "app",
      "deploy",
      "--quiet",
      "--project",
      "$PROJECT_ID"
    ]
    id: "deploy-app"
    waitFor: ["django-test", "decrypt-secret"]
