# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7
        environment:
          SECRET_KEY: =R!&FDaRYy=yt]Y"d"{v3R^mk:ba|JwaOV?;?7]D)7thx,a0:SpS+cU4UFRM63XG
          DB_NAME: app
          DB_PASSWORD: password

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app
          POSTGRES_PASSWORD: password

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            bin/manage.py collectstatic --noinput

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            bin/manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: google/cloud-sdk:219.0.1-alpine
    steps:
      - checkout
      - run: echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
      - run: echo $SECRET | base64 -d > secret.yaml
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud app deploy --quiet --project develop-187803

workflows:
  version: 2
  main:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
