name: CD (production)
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Authenticate GCP
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Prepare secrets
        uses: actions/gcloud/cli@master
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.PROJECT_ID }}
        with:
          args: kms decrypt --ciphertext-file=secrets.yaml.enc --plaintext-file=secrets.yaml --location=global --keyring=ml2lm --key=secret

      - name: Deploy to production
        uses: actions/gcloud/cli@master
        if: success()
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.PROJECT_ID }}
        with:
          args: app deploy --quiet

      - name: Slack notification
        uses: 8398a7/action-slack@v2
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
